# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'LearnRxSwiftMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnRxSwiftMVVM
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'

end
